services:
  ansible-master:
    hostname: ansible-master
    container_name: ansible-master
    image: fallewi/datascientest-labs:ansible
    ports: 
     - ${UBUNTUC_PORT_SSHD}:22
     - ${UBUNTUC_PORT_TTYD}:7681
    privileged: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/ubuntu-c/ansible:/home/ansible
     - ${ANSIBLE_HOME}/ubuntu-c/root:/root
    networks:
     - datascientest-network

  ubuntu1:
    hostname: ubuntu1
    container_name: ubuntu1
    image: fallewi/datascientest-labs:ubuntu
    ports: 
     - ${UBUNTU1_PORT_SSHD}:22
     - ${UBUNTU1_PORT_TTYD}:7681
    privileged: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/ubuntu1/ansible:/home/ansible
     - ${ANSIBLE_HOME}/ubuntu1/root:/root
    networks:
     - datascientest-network

  ubuntu2:
    hostname: ubuntu2
    container_name: ubuntu2
    image: fallewi/datascientest-labs:ubuntu
    ports: 
     - ${UBUNTU2_PORT_SSHD}:22
     - ${UBUNTU2_PORT_TTYD}:7681
    privileged: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/ubuntu2/ansible:/home/ansible
     - ${ANSIBLE_HOME}/ubuntu2/root:/root
    networks:
     - datascientest-network


  centos1:
    hostname: centos1
    container_name: centos1
    image: fallewi/datascientest-labs:centos_stream
    ports: 
     - ${CENTOS1_PORT_SSHD}:22
     - ${CENTOS1_PORT_TTYD}:7681
    privileged: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/centos1/ansible:/home/ansible
     - ${ANSIBLE_HOME}/centos1/root:/root
    networks:
     - datascientest-network

  centos2:
    hostname: centos2
    container_name: centos2
    image: fallewi/datascientest-labs:centos_stream
    ports: 
     - ${CENTOS2_PORT_SSHD}:22
     - ${CENTOS2_PORT_TTYD}:7681
    privileged: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/centos2/ansible:/home/ansible
     - ${ANSIBLE_HOME}/centos2/root:/root
    networks:
     - datascientest-network


networks:
  datascientest-network:
    name: datascientest-network
    # Canonical bridge interface name
    #
    # The setting below provides a friendly name for the bridge interface
    # as seen in the likes of the ip command.  Use at your own discretion
    #
    #driver_opts:
    #  com.docker.network.bridge.name: "datascientest-network"